# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OAHDYDOGCa7mxJiKDO5mGaOL,iv:iezLJ1/f6KcFxxye986Vi0SV+zQdHX7t+rwPU8xTd1s=,tag:IDg/3EUThmwybDZfFdAMkA==,type:str]
    PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:IqM1NTVVmYSHtjdG,iv:K7hhe1mkjgzfXRMXIIloK2JjXZMrwnxJ5+GsSqkeP5o=,tag:n3TXTVmen2YOt0XIlE0dnw==,type:str]
    SECRET_TDIG: ENC[AES256_GCM,data:MQzmKXnYQm1XwzUQ3/XlkKznVTzKndEIJxZL2aFWRUBbDHz6BHkdMZDKfms=,iv:6PUqlQjA2Ub1aavJFkKbaz/WxCz7TPRmU4sB0KX9i3c=,tag:eGiK9JQ/CSEM52gAfo11vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFhWcjZmSStwMjVmQThS
            MlI2d09XSWFVQUxkeDBGdElNOFVVT1VnUTJJCndXQnU5ZTBET2pQYTJ1cHg1anZZ
            UURFQVgxQ0pnZktiRWlBSHl1ZS9UOTgKLS0tIHl1NXJIY1djUjAzWEp3bXZVZ2Fp
            ZU9PQ2xDVExYaitlZ2Z2YlR1aXIwVU0KwrcnvmGuuL1REdUWkbpnpWX43w66Csc1
            /HwOSXHf0VwZiwnpdyTaf6UUHuFspmUEuYlGF/XAXQI9Lqz+yZv4oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-01T07:30:52Z"
    mac: ENC[AES256_GCM,data:r4uwXDckx6jcekoTjVVHGrmCQDt0xAwt3L6qwzs8DXXw6dCroPgLHrnzQXSKqbCzds26UVPMF+3HISUUdoYlkQY0SNkqttue2TIY0c2g4mou2y4rL5+8nX6HbXwN/oakSVvmydcBsJx9bv2bPpYWeGiq5wy2EMbkKO5XS+wf3w4=,iv:76PV978B6ZfGW/sf8s+539XbLaD2WU1nEIfOFn8D4Oo=,tag:OFPht/kAc20PwmufgFGK0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
